spring.application.name=Spring-Coffee-Shop-Project
spring.datasource.url=jdbc:mysql://localhost:3306/spring_coffee_shop_project?autoReconnect=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=7f4c9a2e8d1b6f35a7c0e9d4f2b8a1c6e5f9d3b7c2a8e4f1d6b9c3a7e5f0d2b8c6a4e9f1d7b3c5a8e2f6c9b4d0a7e3f8c1b6d5a9e2f4c7b0d8a3e6f1c9b5d2a7e4f8c0b3d6a9f2e5c7b1d4a8f6c3e0b9d5a2f7c4e1b8d6a9f3c5e7b0d2a4f8c1e6b3d9a5c7f2e4b8d0a6c3f9e1b5d7a2c8f4e6b0d3a9c1f7e5b8d2a4c6f0e9b3d5a1c7e8f2b6d4a9c3
jwt.expiration=86400000

# Email Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kaveeshasithum2003@gmail.com
spring.mail.password=sevzowgeujduzdhh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB